let articleText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et pharetra pharetra massa massa ultricies. Dignissim sodales ut eu sem integer vitae justo. Pulvinar etiam non quam lacus suspendisse faucibus. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Posuere ac ut consequat semper viverra nam libero justo laoreet. Et malesuada fames ac turpis. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Ut faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Arcu dictum varius duis at. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Netus et malesuada fames ac turpis egestas sed tempus.

Urna condimentum mattis pellentesque id nibh tortor id aliquet. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Urna nunc id cursus metus aliquam. Tempor nec feugiat nisl pretium. Amet dictum sit amet justo donec enim diam vulputate ut. Risus in hendrerit gravida rutrum. Ornare arcu odio ut sem nulla pharetra diam sit amet. Elit duis tristique sollicitudin nibh sit amet commodo. Duis tristique sollicitudin nibh sit. Magnis dis parturient montes nascetur ridiculus mus mauris. Et tortor consequat id porta nibh venenatis cras sed. Aliquet sagittis id consectetur purus ut faucibus pulvinar. Nunc eget lorem dolor sed viverra ipsum. Massa placerat duis ultricies lacus sed turpis.

Morbi tincidunt ornare massa eget egestas purus viverra. Sed vulputate mi sit amet mauris. Habitant morbi tristique senectus et netus et malesuada. Turpis cursus in hac habitasse platea dictumst quisque. Integer quis auctor elit sed. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Sit amet nulla facilisi morbi tempus iaculis urna id. At lectus urna duis convallis convallis tellus id interdum velit. Id consectetur purus ut faucibus pulvinar. Id interdum velit laoreet id donec ultrices tincidunt arcu. Viverra ipsum nunc aliquet bibendum. Et odio pellentesque diam volutpat commodo sed. Morbi blandit cursus risus at ultrices mi. Cursus turpis massa tincidunt dui. Proin libero nunc consequat interdum varius sit. Vel pretium lectus quam id leo. A iaculis at erat pellentesque adipiscing commodo elit. Quam nulla porttitor massa id neque aliquam vestibulum morbi. Sit amet aliquam id diam maecenas ultricies mi eget mauris. Et malesuada fames ac turpis egestas sed tempus urna.

Varius morbi enim nunc faucibus a pellentesque sit. Velit dignissim sodales ut eu sem integer vitae. Ornare suspendisse sed nisi lacus sed. Leo duis ut diam quam. Proin sed libero enim sed faucibus turpis in. Vestibulum morbi blandit cursus risus at ultrices mi. Commodo sed egestas egestas fringilla phasellus faucibus. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Vitae ultricies leo integer malesuada nunc vel risus. Mattis rhoncus urna neque viverra justo nec. Non quam lacus suspendisse faucibus interdum posuere. Diam quis enim lobortis scelerisque fermentum. Lacus suspendisse faucibus interdum posuere lorem. Consectetur adipiscing elit duis tristique sollicitudin nibh.

Lacus vel facilisis volutpat est velit egestas dui. Et netus et malesuada fames ac turpis egestas maecenas. Ut consequat semper viverra nam libero justo laoreet sit. Dolor sit amet consectetur adipiscing elit. At urna condimentum mattis pellentesque id nibh. Malesuada fames ac turpis egestas sed tempus. Quis lectus nulla at volutpat diam. Enim ut tellus elementum sagittis vitae. Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Pretium viverra suspendisse potenti nullam. In nibh mauris cursus mattis molestie a iaculis at. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Morbi enim nunc faucibus a pellentesque. Nibh venenatis cras sed felis eget velit aliquet sagittis. Id neque aliquam vestibulum morbi. Donec ultrices tincidunt arcu non. Amet justo donec enim diam vulputate. Cras tincidunt lobortis feugiat vivamus at.`;

document.getElementById("PageContent").innerHTML += FormatArticleText(articleText);

function FormatArticleText(unformatted) {
    let result = "";
    result += "<p class=\"ParagraphText\">";
    result += unformatted.replace("\n", "</p><p class=\"ParagraphText\"> ");
    result += "</p>";
    return result
}